# Site settings
title:          Xiaofeng Yue
description:    "Explorer"
#baseurl:        "/blog"
#url:            ""

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Xiaofeng Yue
  url:          https://xiaofengyue.com
  # email:        placeholder@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       11

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale
